### ISSUE TITLE
No dialog when press OK (first challenge)

### ISSUE THREAD

**Issue by Aholicknight** [philip-karlsson/crackmes#1]
I don't know if this is supposed to happen, but whenever I press `OK` nothing happens. I can't tell if this is a bug or its suppose to happen. 
![2018-10-21_12-08-38](https://user-images.githubusercontent.com/7843719/47270512-1015b180-d52a-11e8-84c2-1dfae270573b.gif)

**Comment by ripxorip** [comment]
Hi! Well the idea is that you shall find the correct user and password which will be able to open the prompt!  I guess I could modify it so you get a popup even when the wrong data is entered.

**Comment by Aholicknight** [comment]
@philip-karlsson That would be very good if you modify it. Thank you!
